### ISSUE TITLE
subsampling lag

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/pyfeat#15]
Should the lag option be supported in more than just the C_K_ij senario? E.g. it would be a fast and easy way to subsample data for WHAM and MBAR as well.

**Comment by franknoe** [comment]
For WHAM and MBAR it is not the lagtime but the timescale given by 1 
over the statistical inefficiency, so it is a conceptually different 
time though.

Am 24/02/15 um 13:23 schrieb ppxasjsm:
>
> Should the lag option be supported in more than just the C_K_ij 
> senario? E.g. it would be a fast and easy way to subsample data for 
> WHAM and MBAR as well.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/pyfeat/issues/15>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by ppxasjsm** [comment]
Ok I agree, which would suggest that the lag option is unique to estiamting count matrices. Everything else would use something like a 'subsample', which would have to be defined as a new parameter.

**Comment by franknoe** [comment]
We should give a time for subsampling (if that option is available), and 
transition-matrix based methods get a lag time. I would keep these two 
things separate, because for transition-matrix-based methods we are not 
even entirely sure that using the subsampling block size equal to the 
lag time is the right thing to do.

Am 24/02/15 um 13:28 schrieb ppxasjsm:
>
> Ok I agree, which would suggest that the lag option is unique to 
> estiamting count matrices. Everything else would use something like a 
> 'subsample', which would have to be defined as a new parameter.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/pyfeat/issues/15#issuecomment-75747737>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
